### PR TITLE
Fix database unit tests.

### PR DESCRIPTION
**Pull request by glv2**

### CODE REVIEW

**Comment by mably** [comment]
@glv2 could you describe a bit what is contained in the two binary test data files?

**Comment by glv2** [comment]
The '178482.dat' file is a raw serialized block (the format used in the blk0001.dat file created by ppcoind).

The 'reorgblocks' file is a bit more complicated (it took me a while to get it right). It is used to test a blockchain reorganization.
It contains 6 raw serialized blocks with the magic id changed (simnet instead of mainnet).
- block 0 must be the 'previous block' of block 1
- block 1 must be the 'previous block' of block 2
- block 0 must be the 'previous block' of block 3
- block 3 must be the 'previous block' of block 4
- block 4 must be the 'previous block' of block 5
- the transactions of blocks 1 and 3 must be different
- the transactions of blocks 2 and 4 must be different

I will put this information in the wiki when I can (I requested an account but I haven't received a password yet).

**Comment by mably** [comment]
Ok, thanx @glv2.  Will PM @FuzzyBearBTC  about your wiki account.

**Comment by mably** [comment]
@glv2, your wiki account has been activated.

**Pull request merged**
