### PR TITLE
Update test data for txscript unit tests.

### PR DESCRIPTION
**Pull request by glv2**
Not all the Bitcoin scripts and transactions test cases have been converted to Peercoin yet, but the new data allows testing many things.

### CODE REVIEW

**Comment by mably** [comment]
@glv2 thanx a lot for all your hard work!

Just noticed a small formatting glitch in txscript\reference_test.go from previous PR.
Remember to run go fmt before pushing your commits to PR.  I forget it myself most of the time ;)

**Comment by mably** [comment]
BTW if some PR is still work in progress, don't forget to tell me so I don't merge it until it's ready.

**Comment by glv2** [comment]
In fact, the line found by 'go fmt' in txscript/reference_test.go ("// github.com/ppcsuite/ppccutil" // TODO: NewTxFromBytes function) can be deleted. I forgot it was still there... :-)

Therefore, you can remove it.

**Comment by mably** [comment]
I think I should stop playing with git, hoping I didn't lose anything in my git interactive rebase to edit that previous commit ;)  Rebasing a public branch is definitely not a good idea, sorry for the annoyance :(

**Comment by glv2** [comment]
As far as I can see we're good, nothing was lost.

**Pull request merged**
